# Generated by Django 5.1.7 on 2026-04-15 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('series', models.CharField(blank=True, max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('grade', models.CharField(blank=True, max_length=32)),
                ('level', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('cover_color', models.CharField(blank=True, max_length=32)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='textbooks/covers/')),
                ('sort_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TextbookComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(default='component', max_length=64)),
                ('sort_order', models.IntegerField(default=0)),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='textbooks.textbook')),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='textbook_components', to='materials.upload')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
