# Generated by Django 5.1.7 on 2026-04-15 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('x', models.PositiveIntegerField(default=0)),
                ('y', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('writing', 'Writing'), ('culture', 'Culture'), ('speaking', 'Speaking')], max_length=32)),
                ('goals', models.JSONField(blank=True, default=list)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('material_count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SkillNodeMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillmap.skillnode')),
            ],
            options={
                'unique_together': {('node', 'material')},
            },
        ),
        migrations.AddField(
            model_name='skillnode',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='skill_nodes', through='skillmap.SkillNodeMaterial', to='materials.material'),
        ),
        migrations.CreateModel(
            name='SkillConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='skillmap.skillnode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='skillmap.skillnode')),
            ],
            options={
                'unique_together': {('from_node', 'to_node')},
            },
        ),
    ]
