# Generated by Django 5.1.7 on 2026-04-15 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('type', models.CharField(max_length=64)),
                ('level', models.CharField(max_length=32)),
                ('grade', models.CharField(blank=True, max_length=32)),
                ('description_short', models.TextField(blank=True)),
                ('description_full', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('difficulty', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('hidden', 'Hidden')], default='draft', max_length=16)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='materials/covers/')),
                ('external_links', models.JSONField(blank=True, default=list)),
                ('featured', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='taxonomy.section')),
                ('subsection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='taxonomy.subsection')),
                ('tags', models.ManyToManyField(blank=True, related_name='materials', to='taxonomy.tag')),
            ],
            options={
                'ordering': ['sort_order', '-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='MaterialFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='materials/files/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('stored_name', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('extension', models.CharField(blank=True, max_length=20)),
                ('size', models.BigIntegerField(default=0)),
                ('kind', models.CharField(default='attachment', max_length=32)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='materials.material')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('extension', models.CharField(blank=True, max_length=20)),
                ('size', models.BigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='materials.material')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='materials.material')),
            ],
            options={
                'unique_together': {('client_id', 'material')},
            },
        ),
        migrations.CreateModel(
            name='MaterialRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='materials.material')),
                ('related_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='materials.material')),
            ],
            options={
                'unique_together': {('material', 'related_material')},
            },
        ),
    ]
